Проверка главной страницы вторично
htmlacademy-htmlcss/1940017-sedona-33 pull request #3
Opened 2022-01-25 19:35 UTC by Bolschakova

2022-01-26 06:45 UTC, Manyaka requested changes

2022-01-26 06:45 UTC, Manyaka commented on catalog.html
> +<!DOCTYPE html>
удали этот файл, потому что в этом дз я проверяю только index

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +             </li>
```suggestion
           </li>
```

не до конца отбьютифаела. Надо бьютифай поставить на сейв файла

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +        <img src="text.svg" alt="Because the Grand<br>Canuon sucks!">
это свг картинка - одна. Одна свг картинка со всей надписью

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +      <article class="preview">
это не статья

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +             </li>
тут картинка ещё

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +             </li>
и ещё внутри unorder list из 3-х пунктов: Жильё/Еда/Сувениры

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +               <h2>Там есть<br>мост дьявола</h2>
тоже тут ещё картинка

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +               </dl>
это не дефинишн лист, п просто unorder, там выше написала куда его вставить

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +             <span><b>Заинтересовались?</b></span>
Не используй в html презентационные теги, типа `<b>, <i>`, тк стили ты задашь через css. Тут идёт разделение: за стили отвечает всегда css, а html - только за разметку страницы

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +             <span><b>Заинтересовались?</b></span>
Также, на что похож этот текст? Может на заголовок? Тогда какого уровня он будет?

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +              <span class="visually-hidden">Поиск гостиницы в Седоне.</span>
Зачем ты тут текст спрятала? Текст видим на этой конпке. С помощью `visually-hidden` ты прячешь что-то от видимости, но оставляешь доступным для скрин-ридера: тут так не надо.

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +             <a class="navigation-link" href="#">
Это кнопка, тк смотри, мы на другую страницу не переходим, а находимся всё на той же страницы, но происходит какое-то действие,  в данном случае - всплывает модальное окно. Поэтому тут делаем кнопку

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +        <span><b>Подпишитесь на рассылку</b></span>
аналогично - комент был выше (два комента)

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +         <input type="email" placeholder="Ваш e-mail"><button class="button" type="submit">Подписаться</button>
нужно ещё добавить `<label>`

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +              <span class="visually-hidden">Facebook</span>
точки внутри `visually-hidden`. Зачем ставить точки, подскажи, пож?

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +              <span class="visually-hidden">Facebook</span>
аналогично поправить где надо по коду

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +        <p class="footer-phone">+7 (812) 812-12-12</p>
телефон переделай на ссылку. Специальную ссылку для телефона

2022-01-26 06:45 UTC, Manyaka commented on index.html
> +        <img class="footer-logo" src="https://htmlacademy.ru/" alt=".htmlacademy">
```suggestion
        <img class="footer-logo" src="https://htmlacademy.ru/" alt="htmlacademy.">
```

2022-01-29 10:41 UTC, Manyaka commented on index.html
> +             </li>
не сделано

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +      <ol class="bloks">
```suggestion
      <ol class="blocks">
```

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +        </ul>
это внутри предыдущего li

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +        <ul class="miniblock">
```suggestion
        <ul class="mini-block">
```

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +            <img scr="" alt="Перевязанная коробка">
```suggestion
            <img scr="" alt="Перевязанная коробка.">
```

всегда ставь точки в альтах

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +            <h3>Жильё</h3>
Отлично, что соблюдаешь порядок заголовков

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +            <img scr="" alt="Перевязанная коробка">
поправь дальше по коду

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +            <img scr="" alt="Перевязанная коробка">
```suggestion
            <img src="" alt="Перевязанная коробка">
```

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +          <img src="" alt="Скалы каньона"
```suggestion
          <img src="" alt="Скалы каньона">
```

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +    </form>
оберни всё это в секшн

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +    </form>
кнопка может существовать без формы. Форма нужна для отправки данных - тут никаких данных нет, просто пользователь нажимает на кнопку и происходит действие на странице, а именно - всплывает модальное окно. Поэтому тут форма не нужна, оставь просто кнопку.

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +    <button class="button" type="submit">Подписаться</button>
содержимое формы тут у тебя выпало из формы - вставь :)

2022-02-01 08:32 UTC, Manyaka commented on index.html
> +              <span class="visually-hidden">Facebook</span>
не сделано

2022-02-01 08:44 UTC, Manyaka requested changes

2022-02-01 08:44 UTC, Manyaka commented on index.html
> +          <span class="visually-hidden">Youtube</span>i
```suggestion
          <span class="visually-hidden">Youtube</span>
```

лишнее затесалось, внимательно проверяй свой код

2022-02-01 08:44 UTC, Manyaka commented on index.html
> +    <a class="footer-contacts-address-phone" href="tel:+78128121212">+7 (812) 812-12-12</a>
отлично сделала телефонную ссылку!

2022-02-01 14:03 UTC, Manyaka commented on index.html
> +        <li class="navigaton-item">
```suggestion
        <li class="navigation-item">
```

2022-02-01 14:03 UTC, Manyaka commented on index.html
> +        <li class="navigaton-item">
остальные тоже поправь, это через замену делается, ищещь слово  с ошибкой и делаешь ему замену на правильное. Интересно, неужели тебе не подчеркнуло ошибку?

2022-02-01 14:03 UTC, Manyaka commented on index.html
> +      <ol class="bloks">
не сделано, русская с не считается :)

2022-02-01 14:07 UTC, Manyaka commented on index.html
> +      <button class="button order-button" type="submit">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
```suggestion
      <button class="button order-button" type="button">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
```
когда кнопка ничего не отправляет, а отправить - по-английски- submit, то её тип становится button - те, это просто кнопка, ну как в сериале: просто Мария.

2022-02-01 14:07 UTC, Manyaka commented on index.html
> +    <button class="button" type="submit">Подписаться</button>
не сделано

2022-02-01 14:53 UTC, Bolschakova commented on index.html
> +        <li class="navigaton-item">
нет в ошибках не указано.

2022-02-02 06:44 UTC, merged