Разметка каталога
htmlacademy-htmlcss/1940017-sedona-33 pull request #4
Opened 2022-02-02 13:38 UTC by Bolschakova

2022-02-03 08:11 UTC, Manyaka requested changes

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +        <li class="navigaton-item">
```suggestion
        <li class="navigation-item">
```

дальше поправить аналогичную орфографическую ошибку

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +    <section class="catalog-filter-housing">
У секции должен быть заголовок

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +                <input id="service3" type="checkbox" name="Wi-Fi">Wi-Fi
имена должны быть английскими буквами, тк это всё уходит на бек, а весь код сайтов состоит из английского язка

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +                <input id="place3" type="radio" name="Апартаменты" value="shaving-supplies">Апартаменты
аналогично, имена - английские буквы. Чем радио отличается от чекбоксов?

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +        </label>
это кнопка

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +    <form action="https://echo.htmlacademy.ru/" method="get"></form>
Это чего?

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +      <span>Найдено гостиниц:</span><output name="number">38</output>
Такое предложение: похоже это на озаглавливание страницы?

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +        <option value="cheap">Сначала дешёвые</option>
```suggestion
        <option value="cheap" selected>Сначала дешёвые</option>
```

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +      <a class="button" href="#"><img src="" alt="Показать карточки."></a>
тут местами перепутано, по дизу видно, что сначала карточки, потом слайдер, потом список

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +      <div class="cards">
див лишний. Сейчас делай по минимуму html тегов, тк если тебе будет не хватать на этапе стилизации, то всегда можно добавить

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +            <a href="#" class="control">от 4000 ₽</a>
Предлагаю посмотреть на это как на текст, а не на ссылки

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +            <form action="https://echo.htmlacademy.ru/" method="post"></form>
Форма тут для чего?

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +            <button type="button" formtarget="housing-cards">Подробнее</button>
```suggestion
            <button type="button">Подробнее</button>
```

это тут лишний атрибут. И подумай ещё в такую сторону: что будет с пользователем, когда он кликнет по Подробнее? Он перейдёт на другую страницу? На этой странице будет более детальное описание гостиницы, например. И если мы переходим на другую страницу - это что? Ссылка?

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +            <button class="checkbox" type="button" formtarget="housing-list">В избранное</button>
```suggestion
            <button class="checkbox" type="button">В избранное</button>
```

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +            <button class="button" type="submit">Рейтинг<output name="sum"> 8,5 </output></button>
Это не рейтинг, в количество звёзд у гостиницы. Дизайнер неудачно изобразил звёздность гостиницы, у пользователей есть паттерн, что когда есть звёзды - надо ставить оценки. Тут не так, это просто информация в виде картинок и текста.

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru/" method="post"></form>
Это форма для чего? Прям у тебя пасхалки такие :) по всему коду разбросаны бесхозные формы :)))))

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +            <a class="pagination-link" href="index.html">1</a>
```suggestion
            <a class="pagination-link" href="">1</a>
```

нет, это не страницы сайта, это страницы для списка найденных гостиниц, как внизу поиска
![Снимок экрана 2022-02-03 в 10 58 19](https://user-images.githubusercontent.com/6417966/152303273-61964bfb-f59b-4c5c-ab5a-b364a7072fbf.jpg)

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +              <span class="visually-hidden"></span>
Что ты тут хотела написать и скрыть?

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +        <span>Гостиниц на странице:</span>
```suggestion
        <p>Гостиниц на странице:</p>
```

спан, это всё-таки для более мелких кусков текста, не для отдельно стоящего куска текста. Для такого лучше параграф

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru/" method="post">
Можно тут без формы

2022-02-03 08:11 UTC, Manyaka commented on catalog.html
> +          <select name="select-control" label="number">
```suggestion
          <select name="select-control" aria-label="Сколько гостиниц показывать на странице:">
```

aria-label и label - это разные вещи

2022-02-03 08:20 UTC, Bolschakova commented on catalog.html
> +      <span>Найдено гостиниц:</span><output name="number">38</output>
Я поняла что это вывод итога поиска, типа счетчика, но информацию как он будет оформлен не нашла. Скорее всего через JS.

2022-02-03 08:26 UTC, Bolschakova commented on catalog.html
> +            <form action="https://echo.htmlacademy.ru/" method="post"></form>
это для кнопки 'Подробнее'

2022-02-03 08:26 UTC, Bolschakova commented on catalog.html
> +            <button type="button" formtarget="housing-cards">Подробнее</button>
Да у меня сначала была ссылка, но потом я решила что когда происходит клик должно произойти расширение окошка с указанными дополнениями, потому сделала кнопку.

2022-02-03 08:27 UTC, Bolschakova commented on catalog.html
> +            <button class="checkbox" type="button" formtarget="housing-list">В избранное</button>
А сдесь получается что карта переходитт на новый лист "Избранное'

2022-02-03 08:31 UTC, Bolschakova commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru/" method="post"></form>
Да я поняла, что форма устанавливается один раз в блоке.

2022-02-03 08:32 UTC, Bolschakova commented on catalog.html
> +              <span class="visually-hidden"></span>
невидимые страницы

2022-02-03 09:02 UTC, Manyaka commented on catalog.html
> +      <span>Найдено гостиниц:</span><output name="number">38</output>
Это аутпут, тот что ты написала, к нему нет вопросов. Как ты думаешь, тут уместен спан, если это больше похоже на заголовок?

2022-02-03 09:10 UTC, Manyaka commented on catalog.html
> +            <form action="https://echo.htmlacademy.ru/" method="post"></form>
не нужно, кнопки работают без формы. Тем более, если у тебя что-то в форме, оно должно быть в форме

2022-02-03 09:18 UTC, Manyaka commented on catalog.html
> +            <button type="button" formtarget="housing-cards">Подробнее</button>
Да, логика правильная, если бы  блочек с гостиницей открывался вниз, то надо было бы делать кнопку, но тут как в магазине, не знаю, пользовалась ли ты Яндекс.Маркетом или чем-то подобным - там обычно это переход на другую страницу. Поэтому тут ссылка

2022-02-03 13:00 UTC, Manyaka commented on catalog.html
> +            <button class="checkbox" type="button" formtarget="housing-list">В избранное</button>
Нет. Вспомни себя - ты когда добавляешь товар в избранное - ты разве переходишь куда-то? У тебя просто обычно пустое сердечко становится полным. Т.е. ты остаешься на этой же странице, просто происходит какое-то действие

2022-02-03 13:01 UTC, Manyaka commented on catalog.html
> +              <span class="visually-hidden"></span>
Нет, они не так скрываются, лучше спан убери, а в ссылке оставь три точки

2022-02-04 05:31 UTC, Manyaka requested changes

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +      <h2 class="visually-hidden">"Фильтр"</h2>
```suggestion
      <h2 class="visually-hidden">Фильтр</h2>
```

для чего взяла заголовок в кавычки?

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +                <input id="service3" type="checkbox" name="Wi-Fi">Wi-Fi
```suggestion
                <input id="service3" type="checkbox" name="wi-fi">Wi-Fi
```

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +                <input id="place1" type="radio" name="hotel" value="shaving-supplies" checked>Гостиница
```suggestion
                <input id="place1" type="radio" name="type-of-housing" value="hotel" checked>Гостиница
```

shaving-supplies - переводится как "принадлежности для бритья" - странное значение типа жилья :)

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +                <input id="place2" type="radio" name="motel" value="shaving-supplies">Мотель
```suggestion
                <input id="place2" type="radio" name="type-of-housing" value="motel">Мотель
```

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +                <input id="place3" type="radio" name="apartments" value="shaving-supplies">Апартаменты
```suggestion
                <input id="place3" type="radio" name="type-of-housing" value="apartments">Апартаменты
```

вот ты поправила 3 коммента. Почему у всех инпут радио я сделала одинаковое имя?

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +          <h3 class="catalog-filter-title">Стоимость, ₽:</h3>
Отлично, что ты следишь за вложенностью заголовков!

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +       <form action="https://echo.htmlacademy.ru/" method="get"></form>
Это моё любимое - бесхозная форма, которая валяется где-то в коде не понятно для чего :)  Удаляй.

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +       <h2>Найдено гостиниц:</h2><output name="number">38</output>
подравняй код

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +      <h1 class="inner-title">Гостиницы Судоны</h1>
```suggestion
      <h1 class="inner-title">Гостиницы Седоны</h1>
```

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +            <p>Гостиница</p><p>От 4000 ₽</p>
```suggestion
            <p>Гостиница</p>
            <p>От 4000 ₽</p>
```

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +            <img src="" alt="4 stars"> <p>Рейтинг 8,5</p>
```suggestion
            <img src="" alt="4 stars."> <p>Рейтинг 8,5</p>
```

Всегда надо ставить точки в альтах

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +            <img src="" alt="4 stars"> <p>Рейтинг 8,5</p>
поправь дальше по коду все аналогичные ошибки

2022-02-04 05:31 UTC, Manyaka commented on catalog.html
> +            <a class="pagination-link" href="housing-list">1</a>
```suggestion
            <a class="pagination-link" href="#">1</a>
```

2022-02-04 13:35 UTC, Bolschakova commented on catalog.html
> +                <input id="place3" type="radio" name="apartments" value="shaving-supplies">Апартаменты
т.к. сдесь идет выбор одного элемента из  группы, потому кнопки имеют одно имя на всех.

2022-02-04 13:42 UTC, Manyaka commented on catalog.html
> +                <input id="place3" type="radio" name="apartments" value="shaving-supplies">Апартаменты
да, правильно

2022-02-04 13:46 UTC, Manyaka requested changes

2022-02-04 13:46 UTC, Manyaka commented on catalog.html
> +              <input id="service1" type="checkbox" name="" checked>
```suggestion
              <input id="service1" type="checkbox" name="pool" checked>
```

2022-02-05 11:16 UTC, merged