Графика всех страниц
htmlacademy-htmlcss/1940017-sedona-33 pull request #5
Opened 2022-02-07 08:24 UTC by Bolschakova

Второй файл связан с ошибками у меня по репозиторию.

2022-02-07 12:06 UTC, Bolschakova commented
![image](https://user-images.githubusercontent.com/94521170/152785030-6d813424-9876-4d69-89c0-371277b19725.png)

2022-02-08 06:28 UTC, Manyaka requested changes

2022-02-08 06:28 UTC, Manyaka commented on catalog.html
> +      <img src="images/cap/logo.png" alt="Город Седона." width="139" height="70">
![Снимок экрана 2022-02-07 в 15 56 32](https://user-images.githubusercontent.com/6417966/152792285-f8519c35-ed02-4614-92d8-6ea150c9f2dc.jpg)

логотип должен быть векторный

2022-02-08 06:28 UTC, Manyaka commented on catalog.html
> +      <img src="images/cap/logo.png" alt="Город Седона." width="139" height="70">
для индекса тоже поправь

2022-02-08 06:28 UTC, Manyaka commented on catalog.html
> +    <img class="footer-logo" src="images/bottom/logo_htmlacademy .svg" alt="htmlacademy.">
```suggestion
    <img class="footer-logo" src="images/bottom/logo-htmlacademy.svg" alt="htmlacademy.">
```

все картинки должны называться через дефис

2022-02-08 06:28 UTC, Manyaka commented on catalog.html
> +    <img class="footer-logo" src="images/bottom/logo_htmlacademy .svg" alt="htmlacademy.">
в индекса тоже поправь

2022-02-08 06:28 UTC, Manyaka commented on index.html
> +  <link rel="stylesheet" href="styles/styles.css/">
это удали, это не нужно ещё

2022-02-08 06:28 UTC, Manyaka commented on index.html
> +    <img src="images/prime/welcome.svg" width="458" height="352" alt="Приглашение в город на фоне скалистого пейзажа.">
Правильно сделала через свг!

2022-02-08 07:10 UTC, Bolschakova commented on catalog.html
> +      <img src="images/cap/logo.png" alt="Город Седона." width="139" height="70">
да я уже сама поняла что ошиблась

2022-02-08 07:17 UTC, Manyaka commented on catalog.html
> +      <img src="images/cap/logo.png" alt="Город Седона." width="139" height="70">
отлично, что ты начинаешь видеть где можно улучшить код! Ты, кстати можешь и улучшать, писать мне в телегу: спрашивать - не проверила ли я и можно подкинуть изменения. Так то в теории ты можешь успеть подкинуть несколько раз свой рефакторинг, пока я не вмержу.

2022-02-08 07:53 UTC, Bolschakova commented
Исправила и добавила на странице каталог одну svg

2022-02-08 08:07 UTC, Manyaka commented on catalog.html
> +            <img src="images/hotels/arrow.svg" width="5" height="8" alt="arrow">
```suggestion
            <img src="images/hotels/arrow.svg" width="5" height="8" alt="arrow">
```

А подумай ещё: это контентная картинка? Или декоративная?

2022-02-08 08:11 UTC, Bolschakova commented on catalog.html
> +            <img src="images/hotels/arrow.svg" width="5" height="8" alt="arrow">
я до оформления картинок вставляла мнемонику но она очень близко к картинкам получалась

2022-02-08 08:13 UTC, Bolschakova commented on catalog.html
> +            <img src="images/hotels/arrow.svg" width="5" height="8" alt="arrow">
если сделать отступы у картинок то наверное лучше сделать декарацию

2022-02-08 08:24 UTC, Manyaka commented on catalog.html
> +            <img src="images/hotels/arrow.svg" width="5" height="8" alt="arrow">
да, оптимальнее сделать декоративно, поэтому img надо удалить

2022-02-08 11:04 UTC, Bolschakova commented
В CSS втавлю картинку

2022-02-08 15:36 UTC, Manyaka requested changes

2022-02-08 15:36 UTC, Manyaka commented on catalog.html
>          </li>
удали это. То, что создаётся с помощью css псевдо-элементов, для них не нужна поддержка в html

2022-02-09 03:59 UTC, merged