Базовая стилизация макета
htmlacademy-htmlcss/1940017-sedona-33 pull request #6
Opened 2022-02-10 14:14 UTC by Bolschakova

Коменты можно скопом.

2022-02-14 10:41 UTC, Manyaka requested changes

2022-02-14 10:41 UTC, Manyaka commented on styles/styles.css
> +@font-face {
стили надо тоже бьютифаить

2022-02-14 10:41 UTC, Manyaka commented on styles/styles.css
> +  src: url("fonts/ptsans-400.woff2") format("woff2");
```suggestion
  src: url("../fonts/ptsans-400.woff2") format("woff2");
```

это какой урл? абсолютный или относительный?

2022-02-14 10:41 UTC, Manyaka commented on styles/styles.css
> +  src: url("fonts/ptsans-400.woff2") format("woff2");
и начиная с этой домашки надо работу проверять в браузере - сразу бы увидела, что шрифты не приехали

2022-02-14 10:41 UTC, Manyaka commented on styles/styles.css
> +  src: url("fonts/ptsans-400.woff2") format("woff2");
поправить везде

2022-02-14 10:42 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 12 33 39](https://user-images.githubusercontent.com/6417966/153848920-7d09c65e-623f-422e-a448-640cd700eb31.jpg)

2022-02-14 10:42 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 12 37 48](https://user-images.githubusercontent.com/6417966/153849023-e5f2c319-9428-4162-b6e1-18fe55cce39e.jpg)

2022-02-14 10:42 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 12 42 35](https://user-images.githubusercontent.com/6417966/153849070-aa4ff26f-5523-4bd0-a6ee-f32bf1961c6a.jpg)

2022-02-14 10:42 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 12 51 32](https://user-images.githubusercontent.com/6417966/153849125-eb26df1c-4190-40d9-8b2b-5d1958da0865.jpg)

2022-02-14 10:43 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 12 55 51](https://user-images.githubusercontent.com/6417966/153849163-6a65890f-ae98-4436-bfed-11f9c3e4c558.jpg)

2022-02-14 10:43 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 12 56 45](https://user-images.githubusercontent.com/6417966/153849210-dfb72d54-30c4-4539-a9df-601b71db74d7.jpg)

2022-02-14 10:45 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 12 59 21](https://user-images.githubusercontent.com/6417966/153849242-49a6f724-0b9d-4288-b9c2-77516dbfc4d6.jpg)

2022-02-14 10:46 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 12 59 57](https://user-images.githubusercontent.com/6417966/153849620-0f32b624-0d72-4630-a402-42c1a8a65968.jpg)

2022-02-14 10:46 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 13 00 49](https://user-images.githubusercontent.com/6417966/153849663-716b6248-5032-4af9-a967-e0013cad1cf4.jpg)

2022-02-14 10:47 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 13 01 51](https://user-images.githubusercontent.com/6417966/153849714-39785997-07db-466a-985d-a577653a2687.jpg)

2022-02-14 10:48 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 13 38 28](https://user-images.githubusercontent.com/6417966/153849788-e9b7a647-3bac-4f28-ab86-ec6ec1c04c9f.jpg)

2022-02-14 10:48 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 13 39 38](https://user-images.githubusercontent.com/6417966/153849914-86dad429-ce17-413b-8ce7-1a60dbab9a2b.jpg)

2022-02-14 10:48 UTC, Manyaka commented
![Снимок экрана 2022-02-14 в 13 40 09](https://user-images.githubusercontent.com/6417966/153849946-4724854a-6bb3-4bc2-8e58-2b0288f1d09e.jpg)

2022-02-17 11:26 UTC, Bolschakova commented
шрифт задан изначально в body и наследуется на все лементы

2022-02-18 05:46 UTC, merged